export const OLD_ACCEPTANCE = 'fear';
export const ACCEPTANCE = 'in love';
export const NEW_ACCEPTANCE = 'acknowledgement';

export const ACCEPTANCE_FIXTURE = {
    OLD_ACCEPTANCE,
    ACCEPTANCE,
    NEW_ACCEPTANCE,
    MIND_ACCEPTANCE: [ OLD_ACCEPTANCE, ACCEPTANCE, NEW_ACCEPTANCE ],
    SOUL_ACCEPTANCE: [ ACCEPTANCE ],
    LOVE_ACCEPTANCE: [ ACCEPTANCE, NEW_ACCEPTANCE ]
};
